packages/aragon-messenger/src/index.js, packages/aragon-messenger/src/providers/MessagePortMessage.js, packages/aragon-messenger/src/providers/WindowMessage.js
Renames the original `PostMessage` provider to `WindowMessage` (since `postMessage()` across windows is the only one that I know of using the `targetOrigin` second parameter).
Note that using `postMessage()` across web workers doesn't seem to send an event with an `event.source`, even though [MDN seems to think it should](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/source). This is in both Chrome and Firefox.
=> Add MessagePort message provider

docs/APP.md, packages/aragon-client/src/index.js
Adds an optional date parameter, as a lot of notifications will only be read after the fact (assuming you won't have the dapp open all the time).
=> Notify: add date parameter

packages/aragon-wrapper/src/cache/index.js
Looks like the localstorage driver is synchronous, so it doesn't return a promise.
=> Cache: fix sync writes

packages/aragon-wrapper/src/cache/index.js
With `startWith`, `observe()` would only send an initial value the next time the cache is updated (which is surprising, I think).
=> Cache: send current value when observing

packages/aragon-client/src/index.js
I got bit by the hot / cold observables flu so I thought it might be less confusing if `store()` was always hot.
Probably biased from past experiences / other relatables, but I feel like a "store" should immediately work (rather than on an explicit subscription).
🤷‍♂️
=> Client: make store observable hot

packages/aragon-messenger/src/jsonrpc.js, packages/aragon-wrapper/src/rpc/handlers/index.js
Currently the cache is broken, as the initial payload is always `undefined`.
~~Not sure if there's any specifics for JSON-RPC, like not allowing undefined payloads.~~
[See below](https://github.com/aragon/aragon.js/pull/67#issuecomment-371220811): apparently JSON RPC doesn't allow `undefined`, so next best is to let the response generator default the payload to `null` if it's not given or is given as `undefined`.
=> Messaging: default response payloads to null

packages/aragon-messenger/src/index.js, packages/aragon-messenger/src/providers/DevMessage.js
This PR contains a small implementation of a message provider I use in my own sandbox to test the communication between apps and the wrapper.
It is used like so:
```js
// Message bus used to pass messages between apps and the wrapper
const bus = new Subject()
// Set up app
const app = new App(
new Messenger(new DevMessage('app', 'wrapper', bus))
)
// Run app
wrapper.runApp(
new DevMessage('wrapper', 'app', bus),
'0xbitconnect'
)
```
Where the first parameter is the provider's own ID, the second is its target ID and the third is an RxJS subject used to pass messages between the different providers.
=> Add development message provider

packages/aragon-client/src/index.js
In the app UIs, we still need the providers to get the `WindowProvider`, so we might as well re-export it :).
=> Client: re-export providers from messenger

packages/aragon-client/src/index.js
Makes this mirror the wrapper's `runApp()`, and allows us to not have to pull in the `Messenger` in clients if we need to change the provider.
=> Client: change proxy interface to take in a provider instead of a messenger

packages/aragon-wrapper/src/index.js
This is probably the worst way to solve this but I don't know.
#💔RxJS
=> Identifier: avoid replaying app operators on emit

packages/aragon-wrapper/abi/aragon/AppProxy.json, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/utils/index.js
Realized with #104 that we'd be breaking all currently deployed apps on Rinkeby 😅.
f355766 provides a fallback hatch to the old proxy implementation, so all aragonOS 3.x apps work.
d1862bb provides slightly better error handling, and avoids including the kernel proxy in the list of apps.
In the future, we could version aragon.js in step with aragonOS, but we should absolutely **AVOID** breaking ABI changes in non-major versions.
Long term, a way to handle these ABI changes from different aragonOS versions is would be to create a connector module that's highly-coupled to aragonOS and let frontend users choose which version of aragonOS they want to use (e.g. we might be on aragonOS 4, but all their apps are still on 3).
=> Make ERC897 changes backwards compatible

packages/aragon-wrapper/abi/aragon/AppProxy.json, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/utils/index.js
Fixes #103.
I've just changed the two usages of `getCode()` since I'm not sure if the goal of the `abi/`s is to be autogenerated by a tool or eventually exported by aragonOS. In any case, it should be noted that the abi of `AppProxy` is slightly out of sync with the current implementation in aragonOS (`AppProxyBase`; most notably, `isForwarder()` isn't available).
=> Update to ERC897 proxy interface

packages/aragon-wrapper/src/evmscript/index.js, packages/aragon-wrapper/src/evmscript/index.test.js
We're removing them from aragonOS so we should remove them here too :).
Closes #111.
=> Remove delegate script encoders

packages/aragon-wrapper/package.json
As result of yesterday's push, the CLI broke as the dependencies of @aragon/wrapper couldn't be resolved because that version of the messenger hadn't been published. 
Published this to NPM already to fix installing the CLI
=> Fix broken @aragon/messenger dependency

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/utils/index.js
Adding `addressesEqual` comparison everywhere to ensure that checks
pass even if only one of the compared addresses are not checksummed.
=> Fix issue with cloudflare non-checksummed addresses

packages/aragon-client/package.json, packages/aragon-messenger/package.json, packages/aragon-wrapper/package.json
Fixes the `npm publish` warning for `prepublish` (deprecated).
This command shouldn't need to be run on a fresh install.
=> prepublish => prepublishOnly

packages/aragon-wrapper/abi/aragon/Kernel.json, packages/aragon-wrapper/src/core/proxy/index.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/utils/index.js
Also required updating the ABI for the Kernel. Once we release aOS 3.2, we should make aragon.js depend on the smart contract package artifacts directly.
=> Fetch DAO initialization block and only filter back to that block

docs/APP.md, packages/aragon-wrapper/package-lock.json, packages/aragon-wrapper/package.json, packages/aragon-wrapper/src/core/proxy/index.js
This closes #125 
With this change, a developer can specify the call's sender address like this:
```javascript 
app.call('foo', 'bar', { from: '0x5f6f7e8cc7346a11ca2def8f827b7a0b612c56a1' })
```
=> Add support for { from: '' } param in call method

packages/aragon-wrapper/src/index.js
Close #135 
Changes how data is stored in the permissions object, rather than `app -> role -> [ entities ]` it now stores an object `app -> role -> { allowedEntities: [ entities ], manager }`
Edit: initially also tracked the permission param hashes, but reverted the changes given that it would have required updating the ABI to the latest aragonOS.
=> Add permission manager ACL representation

packages/aragon-wrapper/src/index.js
Builds on #137 
- Modified `calculateTransactionPath` function so if a `finalForwarder` address is provided, it will always try to forward using that forwarder. In the case of ACL actions that don't have a role, but need the permission manager to perform the action, it passes the permission manager as the `finalForwarder`. Closes #136.
- Added an artifact file for the `ACL` generated locally with the aid of the CLI. This is needed because the ACL app is not currently being published as a regular app.
`wrapper.performACLIntent(method, params)` is used in the same way that intents are used inside regular apps. It will perform a special case of transaction pathing taking permission managers into account (except for `createPermission` which uses a normal role) and then add the transaction.
- …
=> Implements ACL intents

packages/aragon-wrapper/src/index.js
Try a direct transaction if the final forwarder is the sender, and return an empty path instead of throwing an error if we need to calculate a path using the final forwarder, but the given address is not actually a forwarder.
=> Wrapper: Fix ACL direct pathing

packages/aragon-wrapper/src/index.js
The ACL smart contract doesn't fail if granting an already existing permission, and it emits an extra `SetPermission` event. When doing so, the ACL representation of aragon.js was showing some entities  multiple times.
=> wrapper acl: prevent allowed entities from being duplicated

packages/aragon-wrapper/src/index.js
Without `request$` being a subject, the entire chain would get run on every message, across all the event handlers. After converting it into a subject, it only runs through `request$` once per message.
One initialization test of a rinkeby DAO makes this bit go from being invoked ~1000 times to 30.
A useful analogy:
Before
```
--- request$ --> handler_1
--- request$ --> handler_2
...
--- request$ --> handler_n
```
After
```
------> handler_1
/
---- request$ ---> handler_2
\
------> handler_3
```
=> Dedupe request$ across handlers

docs/APP.md, packages/aragon-wrapper/src/index.js
This allows Aragon apps to specify custom transaction values such as `gas`, `value` or `gasPrice` when creating an intent.
=> Support optional transaction parameters in intents

packages/aragon-wrapper/abi/aragon/EVMScriptRegistry.json, packages/aragon-wrapper/artifacts/aragon/EVMScriptRegistry.json, packages/aragon-wrapper/artifacts/aragon/Kernel.json, packages/aragon-wrapper/src/core/aragonOS/index.js, packages/aragon-wrapper/src/interfaces.js
Fixes #132.
Also adds a quickfix for old Rinkeby DAOs that had some of their app IDs generated incorrectly.
=> Add Kernel and EVMScriptRegistry artifacts and add old 0.5 Rinkeby DAO app IDs that were generated incorrectly

docs/APP.md, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/utils/index.js
In order to implement #150 this commit introduces a new `getRecommendedGasLimit()` util
which is calculated based on the estimatedGas by web3 and the latest block
available gas limit.
This is similar to how MetaMask handles gas limit proposals.
We now also prefer using the provided gas that is passed to an intent, if it's higher
than the recommended gas limit. In other words, provided gas is treated as
minimum gas required to perform the transaction/intent.
Closes #150
=> feat(wrapper): introduce getRecommendedGasLimit util

packages/aragon-client/package-lock.json, packages/aragon-client/package.json, packages/aragon-messenger/package-lock.json, packages/aragon-messenger/package.json, packages/aragon-messenger/src/providers/WindowMessage.test.js, packages/aragon-wrapper/package-lock.json, packages/aragon-wrapper/package.json, packages/aragon-wrapper/src/cache/index.js, packages/aragon-wrapper/src/cache/index.test.js, packages/aragon-wrapper/src/core/proxy/index.test.js, packages/aragon-wrapper/src/ens/index.js, packages/aragon-wrapper/src/ens/index.test.js, packages/aragon-wrapper/src/evmscript/index.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js, packages/aragon-wrapper/src/rpc/handlers/external.test.js, packages/aragon-wrapper/src/rpc/handlers/index.js, packages/aragon-wrapper/src/rpc/handlers/index.test.js, packages/aragon-wrapper/src/rpc/handlers/web3-eth.js, packages/aragon-wrapper/test/placeholder.js
This is about adding some unit tests for the wrapper. I just focused on the code that depends on `RxJS`, so we can merge #123 and make sure nothing breaks.
There are a few more functions and files to test though.
TODO:
=> Add unit tests to aragon-wrapper

docs/APP.md, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/utils/index.js
Fixes some problems introduced in #159, related to performing gas estimations on intermediate transaction pathing steps.
Also now `gas` is only treated as `minGas` when the transaction is forwarded, when the intent can be performed directly, if `gas` is provided that's the gas that will be sent in the transaction.
Also tested all possible code paths to verify that transaction pathing with multiple hops works as expected:
=> Transaction pathing: Fix issues introduced with gas estimations

packages/aragon-wrapper/src/index.js
`estimateGas()` expects a given `gas` value to be a number, and the serialization fails when we give it `null`.
=> Wrapper: fix inputs for estimating gas

packages/aragon-wrapper/artifacts/aragon/EVMScriptRegistry.json
Quick fix for the roles for the old EVMScriptRegistry app installed on Aragon Core 0.5 organizations.
Fixes https://github.com/aragon/aragon-apps/issues/476, and accompanying issue to revert this in `aragon.js@3`: https://github.com/aragon/aragon.js/issues/180
=> Fix roles for old EVMScriptRegistry app

packages/aragon-wrapper/package.json, packages/aragon-wrapper/src/templates/index.js
No longer include ABIs from NPM, but load them dynamically from the kits' APM repos.
~It seems that we made some changes to how the client uses the templates API, as it was incompatible.~
Closes #185.
=> Add support v0.6 kits

packages/aragon-wrapper/src/index.js
We should add some sort of logging utility to aragon.js so we can properly log these errors (amongst others), but at least this won't throw away a transaction if evaluating its radspec string failed.
=> wrapper: recover from radspec error

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/utils/index.js
This is sort of a temporary hack as this should probably be built as an extension to radspec in some way, but I'd like to have a bit more of time to think about how that API would look like. Also in the case of addresses we will probably want to do this directly in the client so we can show the entity component.
I'm having doubts about putting the replacements in quotes as you can see in the screenshot, do you think it would look better if we made the text bold @jounih?
Before:
After:
=> Implement radspec postprocessing for humanizing addresses and roles

.size-limit.js, .travis.yml, package-lock.json, package.json, packages/aragon-client/package-lock.json, packages/aragon-messenger/package-lock.json, packages/aragon-wrapper/package-lock.json
This is useful because it:
- prevents an accidental bundle increase 
- helps to measure optimizations like: #208 , #123 
Current output:
```
@aragon/client
Package size: 42.83 KB
Size limit:   45 KB
@aragon/messenger
Package size: 38.35 KB
Size limit:   40 KB
@aragon/wrapper
Package size: 654.92 KB
Size limit:   660 KB
```
from `npm run size:why`
from https://bundlephobia.com/result?p=@aragon/wrapper@3.0.0-beta.3
=> Add size-limit

packages/aragon-wrapper/src/core/proxy/index.js
Fixes the immediate error in https://github.com/aragon/aragon-cli/issues/344 and https://github.com/aragon/aragon/issues/577, as callers of `Proxy.call()` assumed that it was always going to return a promise from the web3 invocation.
This changes the function signature of `Proxy.call()` to always return a promise (rather than sometimes a promise and sometimes an exception).
=> wrapper: fix contract proxy throwing non-async error on unavailable method

packages/aragon-wrapper/package.json, packages/aragon-wrapper/src/cache/index.js, packages/aragon-wrapper/src/cache/index.test.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js
Falls back to a non-persistent, in-memory cache in non-browser environments (e.g. node).
While this doesn't bring feature parity on non-browser environments, it at least avoids the "no storage" error and we don't yet have a use case for supporting caching in those other environments.
=> wrapper: use in-memory localforage driver on non-browser environments

packages/aragon-wrapper/src/cache/index.js, packages/aragon-wrapper/src/cache/index.test.js
Useful when we need to reset app state, or the entire cache state (e.g. aragon/aragon's "Reset state" button).
**TODO**:
=> wrapper: add ability to clear and remove items from cache

packages/aragon-wrapper/src/cache/index.js, packages/aragon-wrapper/src/cache/index.test.js
Builds on #240.
What we used to do was:
- Request `getItem()`
- Discard any changes from `this.changes()` until `getItem()` resolved
- And then subscribe to new changes.
What this PR changes is:
- Request `getItem()`
- If `this.changes()` emits faster than `getItem()` returns, use `this.changes()`
- Otherwise, emit result from `getItem()` and subscribe to `this.changes()`
-----------
The race is important here, as if you requested `getItem()` but the key was set before `getItem()` resolved, you'd get an old item and not know about the new one.
You can see this behaviour in the tests before, where at https://github.com/aragon/aragon.js/pull/242/files#diff-59379f3d6b8c5800ab952d0814382e36R147, some new changes would get thrown away because `getItem()` hadn't returned, and the first value to …
=> wrapper: change cache observe behaviour to race against getItem() and new setItems()

package.json, packages/aragon-client/package.json, packages/aragon-messenger/package.json, packages/aragon-wrapper/package.json
- Pass the `inline` [option to babel](https://babeljs.io/docs/en/babel-cli#compile-with-source-maps) when building the code in `dev` mode 
- Use `dev` mode from top level `build:watch` script
- When linking packages for local development inline sourcemaps are easier for the browser to find/parse. Previously it wasn't working.
=> Add inline sourcemaps when watching for easier debugging

.travis.yml
- Upgrades node version
- Explicitly calls `npm install` instead of letting [travis automatically decide](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#npm-ci-support) to run `npm ci` when it finds a `package-lock.json`
- uses the [travis convention for npm cache](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#caching-with-npm):
> This caches $HOME/.npm precisely when npm ci is the default script command. (See above.)
In all other cases, this will cache node_modules. Note that npm install will still run on every build and will update/install any new packages added to your package.json file.
=> Fix CI and travis

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js, packages/aragon-wrapper/src/utils/AsyncRequestCache.js, packages/aragon-wrapper/src/utils/AsyncRequestCache.test.js, packages/aragon-wrapper/src/utils/index.js
Adds a `AsyncRequestCache` that deduplicates async requests and caches the first successful result. This is really useful for getting information that will stay constant, such as contract values that can never change or contents from ipfs hashes.
Refactors the wrapper's `initApps()` to use this cache and also set up the stage for getting aragonPM repository information.
=> wrapper: deduplicate async requests when fetching app information

.size-limit.js, README.md, packages/aragon-api-react/package.json
- Mention the package in the main README.
- Add it to the size limits.
- Rename its "dev" script to "build:dev".
=> Align aragon-api-react with the other packages

.size-limit.js, README.md, packages/aragon-api-react/README.md, packages/aragon-api-react/package.json, packages/aragon-api-react/src/index.js
Builds on  #269 − please don’t merge before it gets merged.
- Remove the `rxjs` dependency.
- Move `@aragon/api` as a peerDependency.
- Compress the build with Terser.
- Disable `webpack` in the size-limit config for `@aragon/api-react` (see https://github.com/ai/size-limit/issues/79#issuecomment-475728603).
=> @aragon/api-react: remove the rxjs dependency

.gitignore
It's been a while since we stopped commiting the `package-lock.json` into the repo... not sure why it's not in the gitignore.
=> chore: ignore package-lock.jsons

packages/aragon-wrapper/src/index.js
@2color Wondering what you think might be the _least_ confusing.
Currently, when we make these contract proxies, we use the Kernel's `initializationBlock` as their `initializationBlock` (this has large implications when fetching events, because we default to it a the `fromBlock`).
However, this is _technically_ the incorrect block for app proxies, as each of these proxies can have their own `initializationBlock`, and we don't actually need it to be set in changeset as we never fetch events there.
I don't envision us ever having to fetch events here, so I thought it might be clearer to just not set the `initializationBlock`.
=> Wrapper: don't assign initializationBlock on non-kernel proxies when unneeded

packages/aragon-wrapper/src/core/apm/index.js, packages/aragon-wrapper/src/core/aragonOS/index.js, packages/aragon-wrapper/src/core/proxy/index.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/interfaces.js, packages/aragon-wrapper/src/interfaces.test.js
Adds an `installedRepos` observable that emits an array of `InstalledRepos`:
```js
// InstalledRepo:
{
repoAddress: '0x...',
appId: '0x...',
currentVersion: {
version: '1.1.1',
content: {...},
},
latestVersion: {
version: '2.0.0',
content: {...},
},
versions: [
{ version: '1.0.0', contractAddress, contentURI, timestamp },
{...}
]
}
```
Eschews using [`apm.js`](https://github.com/aragon/apm.js/blob/master/src/index.js)'s utilities for more optimized local versions of them due to a few design limitations in `apm.js`:
1. Returns raw `Web3.Contract`s, so we'd have to wrap its events around an Observable (we already have the `Proxy` to do this)
1. Most calls attempt to return the full app info from IPFS (`artifact.json` + `manifest.json`), so they can take quite long to resolve
1. A lot of …
=> Wrapper: add installedRepos observable

docs/QUICK_START.md, docs/README.md
**Changes**
Extracted the `Quick Start` docs to their own file, this way they are less diverged from `hack`.
=> Split quick start doc from intro

packages/aragon-wrapper/src/index.js
This is actually a breadth-first search, due to the `.push()` (rather than `.unshift()`), and on second thought, the breadth-first strategy makes a lot more sense than depth-first.
In the future we could do something smarter, like evaluate depth-first up to `MAX_PATH_SIZE / 2` to optimize for cases where an organization has lots of forwarders installed.
=> Wrapper: clarify comments about forwarding path finding strategy

packages/aragon-wrapper/src/index.js
Fixes https://github.com/aragon/aragon/issues/749.
We should prefer the values obtained from the contract directly (`app`), rather than those fetched from their published `artifact.json` (`appInfo`), in case there's a mismatch (the chain should always be the source of truth).
=> Wrapper: override fetched app info with on-chain values

packages/aragon-wrapper/src/core/aragonOS/index.js, packages/aragon-wrapper/src/core/aragonOS/index.test.js, packages/aragon-wrapper/src/core/aragonOS/kernel.js, packages/aragon-wrapper/src/core/aragonOS/kernel.test.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js, packages/aragon-wrapper/src/radspec/index.js, packages/aragon-wrapper/src/templates/index.js, packages/aragon-wrapper/src/utils/apps.js, packages/aragon-wrapper/src/utils/index.js, packages/aragon-wrapper/src/utils/intents.js, packages/aragon-wrapper/src/utils/transactions.js
Has a few kinks to work out, but works for single-transaction organization upgrades.
=> wrapper: handle intent baskets

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/radspec/index.js
Oops, this wasn't being caught with the radspec refactor.
If we don't know what the function is (e.g. see example issue: https://github.com/aragon/aragon-cli/issues/450), we should return an undecorated version of the step.
=> wrapper: return original step if radspec couldn't be evaluated

packages/aragon-wrapper/src/rpc/handlers/describe-script.js
With the change to how the identifiers are added, and the names being stripped out of the radspec description (technically apps should have access to all this information with #194), we need to temporarily add this back in to the `describe-script` RPC handler.
=> fix: add back name and identifer to describe script

packages/aragon-wrapper/src/index.js
**Changes**
- Moved the `getBlockNumber()` call higher
**Why**
This seems to fix the issue with `rc.6` where the wrapper would initialize, but never emit permissions/apps/etc.
**How**
This might be related to ganache, web3 or `Proxy.events`. It looks like when another web3 function is used between calling `Proxy.events` and connecting/subscribing, it will no longer emit:
```
const someEvents = this.aclProxy.events()
console.log('acc', await this.web3.eth.getAccounts())
someEvents.subscribe(console.log)
```
(it emits if I remove the `getAccounts()` call)
Note: on rinkeby it works without this change 🤷‍♂ 
**If you are modifying the external API of one of the modules, please remember to also change the [documentation](/docs/)**
=> Wrapper: fix initAcl() on localhost

packages/aragon-wrapper/src/index.js
On local chains (e.g. aragen's), there may not have been 100 blocks yet 😅.
cc @0xGabi, not sure if this fixes the local chain issue you were seeing but will keep investigating.
=> wrapper: clamp ACL cached block height to 0 for safety in local chains

docs/APP.md
Adds a bit of consistency, updates links, and reorders sections to place more useful APIs closer to the top. Also uses `api` as the recommended name, to align with `api-react`.
Also fixes https://github.com/aragon/aragon.js/issues/302.
=> Clean up API documentation

docs/APP.md, packages/aragon-api/src/index.js, packages/aragon-api/src/index.test.js, packages/aragon-rpc-messenger/src/index.js, packages/aragon-rpc-messenger/src/index.test.js
As their name implies, `sendAndObserveResponses()` and `sendAndObserveResponse()` only work when they have a subscriber attached to receive the response, otherwise we result in the current confusing "semi-hot" behaviour where an RPC request is initiated immediately (from the app) but whose response (from the client) gets dropped because there's no observer set on the app.
This changes the behaviour of these RPC requests to always make them cold, such that requests are only kicked off once the first subscriber is attached.
**Todo**:
=> messenger: use defer() for observed requests to avoid dropping responses

packages/aragon-api/src/index.js
A couple of improvements to #297.
- 956d722: Now that #305 is merged, we can use `this.accounts()` directly without worrying about the first emission being lost
- d307e44: Supersedes #301; the `new Promise()` also catches the case where `reducer()` throws synchronously, and the `catchError()` operator allows us to log and re-throw the error
- To be on the safe side, opted to re-throw the error and end the `store()` stream for now, rather than silently returning the previous `state` and continuing the reducing
- b451ece: Allow any state reduced from past events to be propagated as the current state, now that the cached state is kept in a separate key
- In the future, we may want to completely move the `state` to be in-memory, since now we're effectively using double the storage (`state` …
=> App state caching: improvements

docs/APP.md, packages/aragon-api-react/package.json, packages/aragon-api/package.json, packages/aragon-api/src/index.js, packages/aragon-rpc-messenger/package.json, packages/aragon-wrapper/package.json, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js, packages/aragon-wrapper/src/rpc/handlers/cache.js
Couple of changes / fixes, especially with race conditions.
I was getting a bit scared that we were flushing store updates without checking that they were first complete, since the IndexedDB API is all async (so that a second `cache()` request wouldn't have a race condition and override the previous one). I'm not certain if I _actually_ saw this happen, but there definitely was some funny business going on at times with the cache.
Also a good reminder for the future (to myself), the past events stream **only** ends when all the observables complete. This can sometimes make it look like an app's done syncing (it's showing all the relevant state), but actually is not yet (e.g. due to the past Vault events being slower than the Finance app's own events).
- 435c3a8: Likely still has a bit of …
=> App state caching: improvements++

packages/aragon-wrapper/src/index.js
`debounceTime` is hard to optimize, because it delays for a set amount of time _every time_ there's an emission (potentially delaying infinitely). I had to pick a value that was _big enough_, but still short enough to see updates.
This led to a lot of churn on the initial loading, as the profiler shows (see after the break).
~~`sampleTime` is a bit easier to control, since it just emits the last value every N seconds, so we can pick a fairly generous amount of time. It also does not emit if no new emissions have come from the source in that time.~~
~~(For reference,  `throttleTime` doesn't work because it throws away potentially new values.)~~
I've since learnt that `throttleTime` has a `trailing` flag that can be set to mimic `sampleTime`, but in a less resource-intensive way (timer only …
=> wrapper: use longer throttleTime instead of shorter debounceTime to throttle installedRepo observable

packages/aragon-wrapper/src/identity/LocalIdentityProvider.js, packages/aragon-wrapper/src/identity/LocalIdentityProvider.test.js
As discussed here: https://github.com/aragon/aragon.js/pull/308#discussion_r291205441
=> Identities autocomplete provider remove check for search term length

packages/aragon-wrapper/src/identity/LocalIdentityProvider.js, packages/aragon-wrapper/src/identity/LocalIdentityProvider.test.js, packages/aragon-wrapper/src/index.js
See https://github.com/aragon/aragon/issues/838.
=> Wrapper: remove clear() functionality from local identity provider as remove() supercedes it

packages/aragon-wrapper/package.json, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/interfaces.js, packages/aragon-wrapper/src/interfaces.test.js, packages/aragon-wrapper/src/utils/transactions.js
Adds the ability to attach pretransactions to an initial forwarder that requires fees (e.g. a [Tollgate](https://github.com/aragonone/tollgate)).
Requires a new release of aragonOS (https://github.com/aragon/aragonOS/pull/539).
=> Wrapper: add ability to apply token approval pretransactions to forwarders requiring fees

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/utils/intents.js
Small fix for when no transaction path could be found for an intent basket.
Fixes the crash that occurs when trying to upgrade all of the [AGP org's](https://mainnet.aragon.org/#/governance.aragonproject.eth/) apps cc @izqui.
=> Wrapper: fix no path found for intent baskets

docs/API.md
**Changes**
When I helped @rperez89 do some work on a new aragon app was difficult to understand how the `web3Eth` function call worked, especially cause the official documentation use it in a different way. I have included a couple of examples to further explain it
=> Add web3Eth examples

packages/aragon-api/src/index.js, packages/aragon-api/src/index.test.js
**Changes**
Updates the `api.store()` behaviour to be a bit more consistent / less surprising.
Changes:
- ⚠️ If `options.init()` is available, use only its returned state to start the reducer (rather than merging its result with the cached state, which may be surprising)
- Make sure `null` is used as the initial state for the `reducer` as well as `options.init`
- Make sure `options.init()` cannot accidentally manipulate the object held in the cache observable
- Improvements to the debug logging
=> API: update behaviour of store() to be more consistent

packages/aragon-api/src/index.js, packages/aragon-api/src/index.test.js, packages/aragon-wrapper/src/index.test.js, packages/aragon-wrapper/src/rpc/handlers/cache.js
As noticed in https://github.com/aragon/aragon.js/issues/357#issuecomment-520136806, this modifies the cache APIs to be leaner; `getCache()` can only return one value anyway and does not need to be hooked up to a long-lived observable on the client's side.
=> API: avoid using cache.observe() for all getCache() requests

docs/API.md, packages/aragon-api/src/index.js, packages/aragon-api/src/index.test.js, packages/aragon-wrapper/src/core/proxy/index.js, packages/aragon-wrapper/src/core/proxy/index.test.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/rpc/handlers/events.js, packages/aragon-wrapper/src/rpc/handlers/events.test.js, packages/aragon-wrapper/src/rpc/handlers/external.js, packages/aragon-wrapper/src/rpc/handlers/external.test.js, packages/aragon-wrapper/src/rpc/handlers/past-events.js, packages/aragon-wrapper/src/rpc/handlers/past-events.test.js, packages/aragon-wrapper/src/utils/events.js
Supercedes https://github.com/aragon/aragon.js/pull/310.
Improves the overall `@aragon/wrapper` implementation to handle aragonAPIv1's RPC requests for events and past events (I've grouped prior beta versions of aragonAPIv2 into aragonAPIv1). Eventually we will be able to remove the old code when aragonAPIv1 is fully deprecated.
Also fleshes out the events RPC to send event names, since this is a breaking RPC change anyway, to allow for https://github.com/aragon/aragon.js/issues/363 in the future.
=> API: allow event options to be passed for events() and pastEvents()

.size-limit.js, packages/aragon-wrapper/package.json
**Changes**
I bumped the web3 dependency up to release 37 from release 33. I've tested and verified that this will support the ability to return tuples from contracts without any further modifications.
=> Web3: upgrade to latest v1

docs/API.md, packages/aragon-api/src/index.js, packages/aragon-api/src/index.test.js, packages/aragon-wrapper/src/rpc/handlers/get-apps.js, packages/aragon-wrapper/src/rpc/handlers/get-apps.test.js
Fixes https://github.com/aragon/aragon.js/issues/312.
See potential breaking changes below (for `getApps()`). @topocount @Schwartz10 this has been made backwards compatible with the current released beta version of aragonAPI that includes `api.getApps()`, but ideally you'll be able to migrate to the new version without too much pain.
Please let me know if there's anything you're missing in the returned app objects for `getApps()` and if it'd be OK to remove the backwards compatibility! I'd like to restrict the API size as much as possible.
----------
Allows a running app to get details about itself, most useful of which is its own proxy address (from there it can pretty much do anything).
The returned object for the current app is only a subset of the available information, since most of …
=> API: get filtered details for current app and all apps

packages/aragon-wrapper/src/index.js
The `isForwarder()` check on each app was broken from the [`web3@1` upgrade](#334) (see [underlying issue](https://github.com/ethers-io/ethers.js/issues/596)). This hotfixes the check so that we override it to be `false` if the app wasn't compiled with `IForwarder`. 
Note that this isn't 100% full-proof; an app could, within reason, dynamically decide to start or stop being a forwarder at one point or another. Also note that having every app be a forwarder _should not_ break anything, it just makes the transaction pathing algorithm more complicated and resource intensive.
Given that no app (that I know of) dynamically switches from being a forwarder to not, I sided with not degrading transaction pathing performance.
=> Wrapper: hotfix isForwarder() check on apps

docs/API.md, packages/aragon-api/src/index.test.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/rpc/handlers/describe-script.js, packages/aragon-wrapper/src/rpc/handlers/get-apps.js, packages/aragon-wrapper/src/rpc/handlers/get-apps.test.js
In addition to https://github.com/aragon/aragon.js/pull/371, adds each app's name and identifier to responses from `getApps()` and `getCurrentApp()`.
=> API: expose app names and identifiers in getApps() and getCurrentApp()

docs/API.md, packages/aragon-api/src/index.js, packages/aragon-api/src/index.test.js
See discussion in https://github.com/aragon/aragon.js/pull/352#discussion_r319780321.
Deprecates the old `getApps()` behaviour and replaces it entirely with `installedApps()`.
Also renames `getCurrentApp()` to `currentApp()` for consistency.
=> API: rename apps apis to installedApps() and currentApp()

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js, packages/aragon-wrapper/src/utils/index.js
Adds `AppProxy`'s events, which is just `ProxyDeposit`, to a running app's ABI.
This allows app reducers to catch `ProxyDeposit` events in `api.store()` and `api.events()`.
=> Wrapper: add AppProxy's events abi to running apps

docs/API.md, packages/aragon-api/src/index.js, packages/aragon-api/src/index.test.js, packages/aragon-wrapper/src/apps/index.js, packages/aragon-wrapper/src/apps/index.test.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js, packages/aragon-wrapper/src/rpc/handlers/index.js, packages/aragon-wrapper/src/rpc/handlers/path.js
**Changes**
Added request handler to the wrapper, then handle path from there and finally connect API and slightly modify API-react to use this new handler from the observable
**If you are modifying the external API of one of the modules, please remember to also change the [documentation](/docs/)**
Pending docs until some approval feedback / polish
TBD
=> API: add path support (navigation)

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/radspec/index.js, packages/aragon-wrapper/src/radspec/postprocess.js
Allows apps like the Agent, which may be invoking actions on other org's apps, to have better radspec results.
Also re-organizes the radspec a bit so that the postprocessing code sits in its own module.
cc @izqui.
=> Wrapper: fallback radspec evaluation to check all installed apps

packages/aragon-api-react/README.md, packages/aragon-api-react/src/index.js
Builds on https://github.com/aragon/aragon.js/pull/326
Receive the complete list of apps installed in the organization.
Example:
```jsx
import { useApps } from '@aragon/api-react'
function App() {
const apps = useApps()
return (
<div>
{apps.map(app => (
<div>{app.appAddress}</div>
))}
</div>
)
}
```
=> @aragon/api-react: useApps()

packages/aragon-api-react/README.md, packages/aragon-api-react/src/index.js
Deprecates the menu-related functionality from `api-react` as the client has stopped supporting these internal APIs.
=> api-react: deprecate menu-related features

docs/API.md, packages/aragon-api-react/README.md, packages/aragon-api/src/index.js, packages/aragon-api/src/index.test.js, packages/aragon-api/src/utils.js, packages/aragon-wrapper/src/core/apm/index.js, packages/aragon-wrapper/src/rpc/handlers/get-apps.js, packages/aragon-wrapper/src/rpc/handlers/get-apps.test.js, packages/aragon-wrapper/src/utils/FileFetcher.js
Adds an `iconSrc` property to any returned app objects from `api.installedApps()` and `api.currentApp()` (if the icons are available).
If there are multiple icons declared in an app's `manifest.json`, this uses the first one for simplicity.
=> Api: add iconSrc of installed apps

packages/aragon-wrapper/artifacts/aragon/ACL.json, packages/aragon-wrapper/artifacts/aragon/EVMScriptRegistry.json, packages/aragon-wrapper/artifacts/aragon/Kernel.json
**Changes**
Add the `transferToVault` function to `Kernel`, `ACL` and `EVMScriptRegistry` artifacts
=> Add transferToVault to Kernel's artifact

docs/WRAPPER.md, packages/aragon-wrapper/src/core/apm/index.js, packages/aragon-wrapper/src/core/apm/repo.js, packages/aragon-wrapper/src/index.js
Allows the IPFS timeout for fetching aragonPM artifacts be parameterized by users through the wrapper's `options.apm.ipfs.fetchTimeout` optional parameter. Like before, defaults to 10s.
cc @0xGabi
=> Wrapper: allow IPFS fetch timeout to be parameterized

docs/API.md, packages/aragon-api/src/index.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/radspec/index.js, packages/aragon-wrapper/src/rpc/handlers/describe-transaction.js, packages/aragon-wrapper/src/rpc/handlers/index.js
Adds an API for describing raw transactions through radspec. Combined with https://github.com/aragon/aragon.js/pull/376, this allows an app, like the Agent, to describe raw transactions to other orgs / contracts into descriptions similar to those found when interacting with the org's own installed apps.
=> Api: describe transactions through radspec

packages/aragon-wrapper/src/index.js
**Changes**
Small change to throw a more specific error message when `app` is not found. 
The previous error was thrown in `createDirectTransactionForApp` and was a little bit misleading: `Could not create transaction due to missing app artifact`. People often thought it was a problem related to IPFS.
- (N/A) I have updated the associated documentation with my changes
=> Wrapper: clarify calculateTransactionPath() error when destination is not installed

packages/aragon-wrapper/src/radspec/index.js, packages/aragon-wrapper/src/rpc/handlers/describe-transaction.js
Fixes #101.
We could also take this opportunity to add tests to `describeTransaction` but I'm not sure where to put them so that they are aligned with the pattern. Also creating stubs for radspec could be additional work outside the scope of this small PR.
=> Wrapper: Add error log when radspec evaluation fails

packages/aragon-wrapper/src/index.js
Forgot to use the `addressesEqual()` utility in these cases previously.
The only real problem that could have occurred would have been the final forwarder and sender check, since both of those are outside parameters given by users, but it's good to be consistent everywhere else we do address comparisons.
=> Wrapper: use addressesEqual() in more places where an address comparison happens

packages/aragon-wrapper/src/utils/transactions.js
**Changes**
Pass the EOA address as `msg.sender` to the `forwardFee` function call.
This is useful for use cases when the fee required to forward an intent is relative to the account that is trying to do so.
As the preTransaction will only be applied when the forwarder requiring a fee is the first one in the transaction path, i think it's safe to assume that the `msg.sender` will be an `EOA` and not another forwarder.
=> Wrapper: pass connected account as msg.sender to forwardFee call

packages/aragon-wrapper/artifacts/aragon/ACL.json, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js, packages/aragon-wrapper/src/rpc/handlers/intent.js, packages/aragon-wrapper/src/utils/transactions.js
Required for https://github.com/aragon/aragon-apps/pull/1025.
Adds the ability for an intent to specify its full method signature, to select a particular overload (rather than it just selecting the first found one in the ABI / artifact, which could change based on the compiler).
Also takes the opportunity to restructure the "sanity checks" for transaction pathing, to streamline its logic and remove redundancies.
Tested with;
- Overloaded functions
- Direct functions
- Indirect, transaction-pathed functions
- Functions with final forwarders (e.g. ACL management); both direct and indirect
=> api: allow intents to be sent with full method signatures

packages/aragon-wrapper/src/index.js
🙈 Oops, the refactor in #403 forgot to take into account the cases where the user had direct permission either from holding the permission or from ANY_ENTITY being set.
=> Wrapper: fix transaction pathing for directly accessible actions

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/utils/intents.js
`getTransactionPathForIntentBasket()` now uses `getACLTransactionPath()` to find transaction paths for intents involving the ACL, which need special information due to how they work (actions are authenticated via managers rather than ACL roles).
Note that this PR does not fix a number of issues with how `getACLTransactionPath()` selects its methods; see https://github.com/aragon/aragon.js/issues/412.
=> Wrapper: fix intent basket pathing when basket includes ACL intents

packages/aragon-wrapper/src/core/apm/index.js, packages/aragon-wrapper/src/core/apm/overrides.js, packages/aragon-wrapper/src/index.js
See https://github.com/aragon/deployments/issues/176.
Saint Fame's organization is currently broken because we assume all installed apps are on published versions.
=> wrapper: handle unpublished version of mainnet Agent v5

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js
Fixes #417.
**Changes**
Support ACL transaction path discovery when performing actions in the ACL obtained from `api.external()` such as:
```
const aclHandler = api.external(aclAddr, aclAbi)
aclHandler.revokePermission(entity, app, role).toPromise()
```
**If you are modifying the external API of one of the modules, please remember to also change the [documentation](/docs/)**
It doesn't change the API
=> Wrapper: support ACL intents for api.external handles

.github/auto_assign.yml
We should move to `CODE_OWNERS` to do this on a more granular level, but that will be done later.
=> Github: update assignees list

docs/API.md, packages/aragon-api-react/README.md, packages/aragon-api/src/index.test.js, packages/aragon-wrapper/src/rpc/handlers/get-apps.js, packages/aragon-wrapper/src/rpc/handlers/get-apps.test.js
Partly addresses #416, fixes https://github.com/aragon/aragon/issues/1283.
For `api.currentApp()` and `api.installedApps()`, I've only added the following to each app:
- ABI: this is obvious; this should be available
- Roles: we should aim to support this over the long term, but I've marked it experimental for now because we may be changing the data structure for roles in the future (and we're not ready to commit to the current structure yet)
=> API: add app's ABI and roles to currentApp() and installedApps()

.size-limit.js, packages/aragon-wrapper/src/core/apm/overrides.js
With Agent v5 being published soon, this override will not be needed anymore.
Opted to keep the function stub in case we have a future situation similar to Agent v5.
Also increases the size-limit; most likely web3.js increased in size in its latest version.
=> Wrapper: remove Agent v5 override

CONTRIBUTING.md, README.md
**Changes**
- Update Aragon Chat links to Spectrum
=> chore: update Aragon Chat links

packages/aragon-wrapper/package.json, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js
This is unlikely to have ever presented a problem (as we generally only support mainnet and rinkeby), but using `web3.eth.getChainId()` is now more canonical.
=> Wrapper: update network() API to return chainId

packages/aragon-wrapper/src/identity/LocalIdentityProvider.js, packages/aragon-wrapper/src/identity/LocalIdentityProvider.test.js
Oops, the `LocalIdentityProvider` not using an `async` declaration meant that some errors could be thrown synchronously, which would end up breaking the entire RPC connection for apps.
=> Wrapper: fix identity resolution throwing synchronously rather than asynchronously

.size-limit.js, packages/aragon-wrapper/artifacts/aragon/Kernel.json
**Changes**
Modifies the Kernel.json artifact, adding a new role with the name `Manage profile` and id `MANAGE_PROFILE_ROLE`.
**If you are modifying the external API of one of the modules, please remember to also change the [documentation](/docs/)**
=> Add new MANAGE_PROFILE_ROLE for DAO Profiles

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/radspec/postprocess.js
Allows for `annotatedDescriptions` to appear even if there is only one text/address/app node in the description.
=> Radspec: add annotations for EVMScript descriptions even if they're single nodes

packages/aragon-wrapper/src/core/apm/overrides.js
See https://github.com/aragon/aragon-apps/pull/1183
=> Wrapper: override unlisted Agent with ERC-1155 support with v5 metadata

packages/aragon-api/src/index.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js, packages/aragon-wrapper/src/rpc/handlers/external.js, packages/aragon-wrapper/src/rpc/handlers/external.test.js, packages/aragon-wrapper/src/utils/transactions.js
"ABI fragment" is a much better name for these method descriptors, as is used in [ethers's terminology](https://docs.ethers.io/v5/api/utils/abi/fragments/).
=> api, wrapper: rename `methodJsonDescription` to `methodAbiFragment`

packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js, packages/aragon-wrapper/src/utils/abi.js, packages/aragon-wrapper/src/utils/apps.js, packages/aragon-wrapper/src/utils/transactions.js
Fixes https://github.com/aragon/aragon.js/issues/412.
Deduplicates ABI or artifact searching logic where possible. The consolidation also allows us to make sure we handle some edge cases correct, e.g. fallback functions or incomplete method signatures (where we use method names rather than full signatures).
It's still not the nicest as we don't clearly delineate when an ABI fragment or a raw method signature should be used due to everything being a public interface, so we end up doing the method search multiple times.
=> wrapper: consolidate and deduplicate ABI and method searching
