package-lock.json, package.json, test/helpers/deploy.js, test/helpers/provider.js
Adds two test helpers, `provider` and `deploy` that set up a devnet and deploys artifacts.
Closes #5
=> Add test helpers to set up devnet in CI

package.json, packages/aragon-client/package.json, packages/aragon-messenger/package.json, packages/aragon-wrapper/package.json
Still doesn't pass CI cause there's some weird `warning  @memberof reference to Cache not found` errors from `documentation`, but it's closer...
=> Lint only the source files

package.json
Will make it easier to build / watch the three libraries together.
=> Add build and build:watch global tasks

packages/aragon-wrapper/src/index.js
=> Identifier: fix infinite loop on adding identifier

packages/aragon-client/src/index.js
Defers event observables so they're cold until subscribed to (to avoid losing events), and merges an array of given event observables with the app's events.
=> Allow client store to take in other event streams

.travis.yml, package-lock.json, packages/aragon-client/package-lock.json, packages/aragon-messenger/package-lock.json, packages/aragon-messenger/package.json, packages/aragon-messenger/src/index.js, packages/aragon-messenger/src/index.test.js, packages/aragon-messenger/src/jsonrpc.test.js, packages/aragon-messenger/src/providers/DevMessage.test.js, packages/aragon-messenger/src/providers/MessagePortMessage.test.js, packages/aragon-messenger/src/providers/Provider.test.js, packages/aragon-messenger/src/providers/WindowMessage.js, packages/aragon-messenger/src/providers/WindowMessage.test.js, packages/aragon-messenger/test/placeholder.js, packages/aragon-wrapper/package-lock.json
This is work in progress, part of #18 , but before I continue, which mocking library to use? sinon.js?
=> Add unit tests to aragon-messenger

packages/aragon-wrapper/.babelrc, packages/aragon-wrapper/abi/aragon/ACL.json, packages/aragon-wrapper/artifacts/aragon/ACL.json, packages/aragon-wrapper/package.json, packages/aragon-wrapper/src/core/aragonOS/index.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/interfaces.js, packages/aragon-wrapper/src/rpc/handlers/intent.js, packages/aragon-wrapper/src/utils/index.js
=> Inline ABIs / artirfacts JSON files

packages/aragon-wrapper/src/index.js
Exposes a function that returns the transaction path for ACL actions.
=> wrapper: Expose getACLTransactionPath

README.md
Aragon Core => aragonOS
Aragon web application => Aragon
=> README: update “Basic Overview”

packages/aragon-client/package-lock.json, packages/aragon-client/package.json, packages/aragon-client/src/index.js, packages/aragon-client/src/index.test.js, packages/aragon-client/test/placeholder.js
Related: https://github.com/aragon/aragon.js/pull/147 , #129
=> Unit test aragon-client's usage of RxJS

.gitignore, packages/aragon-client/package-lock.json, packages/aragon-client/package.json, packages/aragon-messenger/package-lock.json, packages/aragon-messenger/package.json, packages/aragon-wrapper/package-lock.json, packages/aragon-wrapper/package.json, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js
- Adds a path to `standard`, to avoid linting built files
- Adds `documentation`, to lint jsdoc
=> Fix lint (again)

packages/aragon-wrapper/src/index.js
This is going to be necessary for #145 and this part of aragon.js keeps changing, so I wanted to get it into the main branch so that I don't have to keep re merging it.
=> Isolate functionality to find a forwarder to perform an action

docs/WRAPPER.md, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js
Just doing the basic check to see if there's an ACL since there isn't a helper function for this yet, may want to open a new issue for if/when the isDAO function exists.
Fixes #64.
=> 64 error on bad dao

packages/aragon-wrapper/src/index.js
- Unifies the annotation format across all the different types (text, addresses, bytes, apps, roles) so that they're all in the format of `{ type, value }`
- Adds two types (generic addresses and bytes)
- Simplifies the parsing implementation
=> wrapper: refactor radspec annotations

packages/aragon-client/.babelrc, packages/aragon-client/package.json, packages/aragon-messenger/.babelrc, packages/aragon-messenger/package.json, packages/aragon-wrapper/.babelrc, packages/aragon-wrapper/package.json
Similar to https://github.com/aragon/aragon/pull/471.
=> chore: unify browserslist

docs/WRAPPER.md, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js
This should fix the error that was occurring with issue 130. It might make sense to change the variable names but I think they're probably better as is since there may be other options added at a later time.
Fixes #130.
=> #130 tweak wrapper options

docs/APP.md
Copies over the changes in https://github.com/aragon/hack/pull/92 and https://github.com/aragon/hack/pull/93 since this is where these docs live now.
cc @cslarson
=> docs: update APP.md

packages/aragon-wrapper/src/cache/index.test.js
See https://github.com/aragon/aragon.js/pull/242#discussion_r260691147
=> wrapper: remove unnecessary wait in cache test

packages/aragon-wrapper/src/index.js
Fixes #235.
Turns out the transaction pathing algorithm is sufficiently smart, we just weren't handling the 0 case correctly (resulting in an infinite loop).
The reason we can't rely on permissions data once we start looking for forwarding path is because those aren't determined by permissions; we have to check `canForward()` for each step.
An additional optimization we could make is cache which forwarders can be linked together, but this seems premature since there's unlikely to be very large paths at this point.
=> fix: avoid infinitely looping through forwarders when looking for a transaction path

packages/aragon-wrapper/src/evmscript/index.test.js, packages/aragon-wrapper/src/index.js, packages/aragon-wrapper/src/index.test.js
See schema for callsscript data: https://github.com/aragon/aragonOS/blob/dev/contracts/evmscript/executors/CallsScript.sol#L28.
Fixes #260.
=> wrapper: fix callsscripts decoding

packages/aragon-wrapper/src/identity/LocalIdentityProvider.js, packages/aragon-wrapper/src/identity/LocalIdentityProvider.test.js
=> Use indexOf instead of regex

packages/aragon-api/src/index.js, packages/aragon-api/src/utils.js
Avoids logging debugging hints in production.
=> api: only log debug messages on development environment

.travis.yml, package.json, packages/aragon-api/package.json, packages/aragon-rpc-messenger/package.json, packages/aragon-wrapper/package.json
Fixes #216.
Also takes the opportunity to upgrade ava to v2.
=> Add coverage reporting

docs/WRAPPER.md
Cosmetic change to organize the identity provider documentation in a similar fashion to the other docs.
=> Wrapper: fix docs for identity providers

packages/aragon-wrapper/src/index.js
See https://github.com/aragon/aragon/issues/892.
=> Wrapper: handle invalid apps being installed in an organization

docs/API.md
=> Docs: update store API docs for aragonAPIv2

packages/aragon-wrapper/src/radspec/index.js
=> Wrapper: fix radspec evaluation when upgrading repos

packages/aragon-wrapper/src/interfaces.js
=> Wrapper: include hatch.aragonpm.eth's native packages

packages/aragon-wrapper/src/index.js
=> Wrapper: fix describing organization upgrades

packages/aragon-wrapper/src/utils/transactions.js
=> Wrapper: fix transaction creation failing due to fallback functions not having inputs declared in the ABI

packages/aragon-api-react/README.md
Small updates to clarify the api-react docs.
=> api-react: update docs

packages/aragon-wrapper/src/radspec/postprocess.js
Updates the descriptions with these nicer quotes than `'` :).
=> Wrapper: update post-processed radspec to use fancy quotes

.github/stale.yml
Aligns to the other repos with the stale bot enabled.
=> chore: update stale bot

packages/aragon-wrapper/package.json, packages/aragon-wrapper/src/radspec/index.js, packages/aragon-wrapper/yarn.lock
This one still pending the PR https://github.com/aragon/radspec/pull/120 being released as npm package and update dependency accordingly..
=> DAO-240: pass currency information to radspec
